// vue/MessageActionToolbar.vue
<template>
  <div :class="['flex items-center gap-1 text-zinc-400 dark:text-zinc-500 text-xs mt-1.5 select-none', className]">
    <!-- Branch Navigator -->
    <div
      v-if="totalBranches && totalBranches > 1 && branchIndex !== undefined"
      class="flex items-center gap-0.5 mr-2 bg-zinc-100 dark:bg-zinc-800/80 px-1.5 py-0.5 rounded-md text-[11px] font-mono text-zinc-600 dark:text-zinc-400"
    >
      <button
        type="button"
        :disabled="branchIndex <= 0"
        @click="$emit('branchChange', branchIndex - 1)"
        class="hover:text-zinc-900 dark:hover:text-zinc-100 disabled:opacity-30 disabled:pointer-events-none p-0.5"
        title="Previous version"
      >
        <UiIcon name="chevron-left" :size="14" />
      </button>
      <span>{{ branchIndex + 1 }}/{{ totalBranches }}</span>
      <button
        type="button"
        :disabled="branchIndex >= totalBranches - 1"
        @click="$emit('branchChange', branchIndex + 1)"
        class="hover:text-zinc-900 dark:hover:text-zinc-100 disabled:opacity-30 disabled:pointer-events-none p-0.5"
        title="Next version"
      >
        <UiIcon name="chevron-right" :size="14" />
      </button>
    </div>

    <!-- Copy -->
    <button
      type="button"
      @click="handleCopy"
      class="p-1 hover:text-zinc-700 dark:hover:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors"
      title="Copy response"
    >
      <UiIcon v-if="copied" name="check" :size="16" class="text-emerald-500" />
      <UiIcon v-else name="copy" :size="16" />
    </button>

    <!-- Retry / Regenerate -->
    <button
      v-if="showRetry"
      type="button"
      @click="$emit('retry')"
      class="p-1 hover:text-zinc-700 dark:hover:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors"
      title="Regenerate response"
    >
      <UiIcon name="refresh" :size="16" />
    </button>

    <!-- Thumbs Up / Down -->
    <template v-if="role === 'assistant'">
      <button
        type="button"
        @click="handleThumb('up')"
        :class="[
          'p-1 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors',
          feedback === 'up' ? 'text-blue-500' : 'hover:text-zinc-700 dark:hover:text-zinc-200'
        ]"
        title="Good response"
      >
        <UiIcon name="thumbs-up" :size="16" />
      </button>
      <button
        type="button"
        @click="handleThumb('down')"
        :class="[
          'p-1 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors',
          feedback === 'down' ? 'text-rose-500' : 'hover:text-zinc-700 dark:hover:text-zinc-200'
        ]"
        title="Bad response"
      >
        <UiIcon name="thumbs-down" :size="16" />
      </button>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import UiIcon from './UiIcon.vue';

const props = withDefaults(
  defineProps<{
    content: string;
    role?: 'assistant' | 'user' | string;
    showRetry?: boolean;
    branchIndex?: number;
    totalBranches?: number;
    className?: string;
  }>(),
  {
    role: 'assistant',
    showRetry: true,
    className: ''
  }
);

const emit = defineEmits<{
  (e: 'retry'): void;
  (e: 'feedback', type: 'up' | 'down'): void;
  (e: 'branchChange', index: number): void;
}>();

const copied = ref(false);
const feedback = ref<'up' | 'down' | null>(null);

const handleCopy = async () => {
  await navigator.clipboard.writeText(props.content);
  copied.value = true;
  setTimeout(() => (copied.value = false), 2000);
};

const handleThumb = (type: 'up' | 'down') => {
  const next = feedback.value === type ? null : type;
  feedback.value = next;
  if (next) emit('feedback', next);
};
</script>

// react/MessageActionToolbar.tsx
import React, { useState } from "react";
import { Copy, Check, RotateCcw, ThumbsUp, ThumbsDown, ChevronLeft, ChevronRight } from "./UiIcon";

export interface MessageActionToolbarProps {
  content: string;
  role?: "assistant" | "user" | string;
  onRetry?: () => void;
  onFeedback?: (type: "up" | "down") => void;
  branchIndex?: number;
  totalBranches?: number;
  onBranchChange?: (nextIndex: number) => void;
  className?: string;
}

export const MessageActionToolbar: React.FC<MessageActionToolbarProps> = ({
  content,
  role = "assistant",
  onRetry,
  onFeedback,
  branchIndex,
  totalBranches,
  onBranchChange,
  className = "",
}) => {
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState<"up" | "down" | null>(null);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleThumb = (type: "up" | "down") => {
    const next = feedback === type ? null : type;
    setFeedback(next);
    if (onFeedback && next) onFeedback(next);
  };

  return (
    <div
      className={`flex items-center gap-1 text-zinc-400 dark:text-zinc-500 text-xs mt-1.5 select-none ${className}`}
    >
      {/* Branch Navigator (if multiple versions exist) */}
      {totalBranches && totalBranches > 1 && branchIndex !== undefined && onBranchChange && (
        <div className="flex items-center gap-0.5 mr-2 bg-zinc-100 dark:bg-zinc-800/80 px-1.5 py-0.5 rounded-md text-[11px] font-mono text-zinc-600 dark:text-zinc-400">
          <button
            type="button"
            disabled={branchIndex <= 0}
            onClick={() => onBranchChange(branchIndex - 1)}
            className="hover:text-zinc-900 dark:hover:text-zinc-100 disabled:opacity-30 disabled:pointer-events-none p-0.5"
            title="Previous version"
          >
            <ChevronLeft className="w-3 h-3" />
          </button>
          <span>
            {branchIndex + 1}/{totalBranches}
          </span>
          <button
            type="button"
            disabled={branchIndex >= totalBranches - 1}
            onClick={() => onBranchChange(branchIndex + 1)}
            className="hover:text-zinc-900 dark:hover:text-zinc-100 disabled:opacity-30 disabled:pointer-events-none p-0.5"
            title="Next version"
          >
            <ChevronRight className="w-3 h-3" />
          </button>
        </div>
      )}

      {/* Copy */}
      <button
        type="button"
        onClick={handleCopy}
        className="p-1 hover:text-zinc-700 dark:hover:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors"
        title="Copy response"
      >
        {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
      </button>

      {/* Retry / Regenerate */}
      {onRetry && (
        <button
          type="button"
          onClick={onRetry}
          className="p-1 hover:text-zinc-700 dark:hover:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors"
          title="Regenerate response"
        >
          <RotateCcw className="w-3.5 h-3.5" />
        </button>
      )}

      {/* Thumbs Up / Down */}
      {role === "assistant" && (
        <>
          <button
            type="button"
            onClick={() => handleThumb("up")}
            className={`p-1 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors ${
              feedback === "up" ? "text-blue-500" : "hover:text-zinc-700 dark:hover:text-zinc-200"
            }`}
            title="Good response"
          >
            <ThumbsUp className="w-3.5 h-3.5" />
          </button>
          <button
            type="button"
            onClick={() => handleThumb("down")}
            className={`p-1 hover:bg-zinc-100 dark:hover:bg-zinc-800/60 rounded-md transition-colors ${
              feedback === "down" ? "text-rose-500" : "hover:text-zinc-700 dark:hover:text-zinc-200"
            }`}
            title="Bad response"
          >
            <ThumbsDown className="w-3.5 h-3.5" />
          </button>
        </>
      )}
    </div>
  );
};
